import { Translations } from "@/models/translations"

export const appTranslations: Translations = {
  en: {
    clickToCopy: "Click to Copy",
    hasCopiedPassword: "Password is copied",
    inputPlaceholder: "eg. '-' or '?'",
    promptToAddWords: "Add words",
  },
  fi: {
    salasanakone: "Salasanakone",
    ok: "Ok",
    update: "Päivitä",
    new: "Uusi",
    tryAgain: "Yritä uudelleen",
    useWords: "Käytä sanoja",
    useCharacters: "Käytä merkkejä",
    useUppercase: "Isot kirjaimet",
    useNumbers: "Numerot",
    useDenominator: "Välimerkit",
    strengthDefault: "Arvio",
    strengthAwful: "Surkea",
    strengthBad: "Huono",
    strengthOk: "Ok",
    strengthGood: "Hyvä",
    strengthGreat: "Loistava",
    timeToCrack: "Murtamisaika",
    clickToCopy: "Kopioi Salasana Klikkaamalla",
    hasCopiedPassword: "Kopioitu",
    inputPlaceholder: 'Esim. "-" tai "?" tai "3!"',
    promptToAddWords: "Lisää sanoja",
    lengthOfPassPhrase: "Pituus: {passLength} sanaa",
    lengthOfPassWord: "Pituus: {passLength} merkkiä",
    leaveFeedback: "Jätä palaute",
    thanksForFeedback: "Kiitos palautteesta",
    thanksForFeedbackLeaveAnother:
      "Kiitos jos annoit palautetta, voit antaa\nuuden palautteen klikkaamalla.",
    visitMySite: "Vieraile sivuillani",
    share: "Jaa",
    moreInfo: "Lisätietoja",
    resultHelperLabel: "Salasana, jonka voi kopioida napauttamalla",
    errorNoGeneration: "Jotain meni vikaan... Salasanaa ei luotu.",
    tryToRefresh: "Koeta päivittää sivu.",
    updateToNewVersion: "Uusi versio saatavilla. Päivitä sivu napauttamalla.",
    worksOffline: "Sivusto toimii nyt myös ilman verkkoyhteyttä.",
    somethingWentWrong: "Jotain meni vikaan.",
  },
}
